#!/usr/bin/env bash
# Loop through the files in the current directory

for file in *; 
do
    # Check if the file is not hidden and is a regular file
    if [ ! -f "$file" ] || [[ "$file" == .* ]]; then
        continue
    fi
    
    # Extract the part of the name after the first dash
    name=$(echo "$file" | cut -d '-' -f 2-)
    
    # Print the formatted output
    echo "$name"
done
