#!/usr/bin/env bash
# Loop through the files in the current directory

for file in *; 
do
    if [ ! -f "$file" ] || [[ "$file" == .* ]]; then
        continue
    fi
    
    name=$(echo "$file" | cut -d '-' -f 2-)
    
    echo "$name"
done
